# Server
server.port=${PORT:8080}

# PostgreSQL - Render
spring.datasource.url=${jdbc:postgresql://moveease_db_3ywh_user:6F6iGUKXYxb55NNIUBrwzhWa2DUIxEgq@dpg-d8jridrbc2fs73a0649g-a.singapore-postgres.render.com/moveease_db_3ywh}
spring.datasource.username=${moveease_db_3ywh}
spring.datasource.password=${6F6iGUKXYxb55NNIUBrwzhWa2DUIxEgq}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.hikari.maximum-pool-size=2